language: c
before_install:
- "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16"
- sleep 3
- export DISPLAY=:1.0
- wget http://downloads.arduino.cc/arduino-1.8.9-linux64.tar.xz
- tar xf arduino-1.8.9-linux64.tar.xz
- sudo mv arduino-1.8.9 /usr/local/share/arduino
- sudo ln -s /usr/local/share/arduino/arduino /usr/local/bin/arduino

# Arduino IDE adds a lot of noise caused by network traffic, trying to firewall it off
- sudo iptables -P INPUT DROP
- sudo iptables -P FORWARD DROP
- sudo iptables -P OUTPUT ACCEPT
- sudo iptables -A INPUT -i lo -j ACCEPT
- sudo iptables -A OUTPUT -o lo -j ACCEPT
- sudo iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

install:
- ln -s $PWD /usr/local/share/arduino/libraries/SparkFun_TMP117_Arduino_Library
- arduino --pref "boardsmanager.additional.urls=https://raw.githubusercontent.com/sparkfun/Arduino_Boards/master/IDE_Board_Manager/package_sparkfun_index.json,https://adafruit.github.io/arduino-board-index/package_adafruit_index.json" --save-prefs 3>&1
- arduino --install-boards SparkFun:samd
- arduino --install-boards SparkFun:apollo3
- arduino --install-boards SparkFun:avr
- arduino --install-boards adafruit:avr

script:
#compile for SparkFun RedBoard
- echo Compiling for SparkFun RedBoard...
- arduino --verify --board SparkFun:avr:RedBoard $PWD/examples/Example1_BasicReadings/Example1_BasicReadings.ino
- arduino --verify --board SparkFun:avr:RedBoard $PWD/examples/Example2_AlertStatuses/Example2_AlertStatuses.ino
- arduino --verify --board SparkFun:avr:RedBoard $PWD/examples/Example3_SetOffsetTemperatureValue/Example3_SetOffsetTemperatureValue.ino
- arduino --verify --board SparkFun:avr:RedBoard $PWD/examples/Example4_SetConversionMode/Example4_SetConversionMode.ino
- arduino --verify --board SparkFun:avr:RedBoard $PWD/examples/Example5_SetAlertModeTemperatureLimits/Example5_SetAlertModeTemperatureLimits.ino
- arduino --verify --board SparkFun:avr:RedBoard $PWD/examples/Example6_SetConversionCycleTime/Example6_SetConversionCycleTime.ino
# - arduino --verify --board SparkFun:avr:RedBoard $PWD/examples/Example7_AdvancedI2CFunctions/Example7_AdvancedI2CFunctions.ino

#compile for SparkFun Artemis
- echo Compiling for SparkFun Artemis...
- arduino --verify --board SparkFun:apollo3:amap3redboard $PWD/examples/Example1_BasicReadings/Example1_BasicReadings.ino
- arduino --verify --board SparkFun:apollo3:amap3redboard $PWD/examples/Example2_AlertStatuses/Example2_AlertStatuses.ino
- arduino --verify --board SparkFun:apollo3:amap3redboard $PWD/examples/Example3_SetOffsetTemperatureValue/Example3_SetOffsetTemperatureValue.ino
- arduino --verify --board SparkFun:apollo3:amap3redboard $PWD/examples/Example4_SetConversionMode/Example4_SetConversionMode.ino
- arduino --verify --board SparkFun:apollo3:amap3redboard $PWD/examples/Example5_SetAlertModeTemperatureLimits/Example5_SetAlertModeTemperatureLimits.ino
- arduino --verify --board SparkFun:apollo3:amap3redboard $PWD/examples/Example6_SetConversionCycleTime/Example6_SetConversionCycleTime.ino
- arduino --verify --board SparkFun:apollo3:amap3redboard $PWD/examples/Example7_AdvancedI2CFunctions/Example7_AdvancedI2CFunctions.ino

#compile for SparkFun SAMD
- echo Compiling for SparkFun SAMD...
- arduino --verify --board SparkFun:samd:samd51_thing_plus $PWD/examples/Example1_BasicReadings/Example1_BasicReadings.ino
- arduino --verify --board SparkFun:samd:samd51_thing_plus $PWD/examples/Example2_AlertStatuses/Example2_AlertStatuses.ino
- arduino --verify --board SparkFun:samd:samd51_thing_plus $PWD/examples/Example3_SetOffsetTemperatureValue/Example3_SetOffsetTemperatureValue.ino
- arduino --verify --board SparkFun:samd:samd51_thing_plus $PWD/examples/Example4_SetConversionMode/Example4_SetConversionMode.ino
- arduino --verify --board SparkFun:samd:samd51_thing_plus $PWD/examples/Example5_SetAlertModeTemperatureLimits/Example5_SetAlertModeTemperatureLimits.ino
- arduino --verify --board SparkFun:samd:samd51_thing_plus $PWD/examples/Example6_SetConversionCycleTime/Example6_SetConversionCycleTime.ino
# - arduino --verify --board SparkFun:samd:samd51_thing_plus $PWD/examples/Example7_AdvancedI2CFunctions/Example7_AdvancedI2CFunctions.ino

#compile for Adafruit Pro Trinket 5
- echo Compiling for AdaFruit Pro Trinket 5...
- arduino --verify --board adafruit:avr:protrinket5 $PWD/examples/Example1_BasicReadings/Example1_BasicReadings.ino
- arduino --verify --board adafruit:avr:protrinket5 $PWD/examples/Example2_AlertStatuses/Example2_AlertStatuses.ino
- arduino --verify --board adafruit:avr:protrinket5 $PWD/examples/Example3_SetOffsetTemperatureValue/Example3_SetOffsetTemperatureValue.ino
- arduino --verify --board adafruit:avr:protrinket5 $PWD/examples/Example4_SetConversionMode/Example4_SetConversionMode.ino
- arduino --verify --board adafruit:avr:protrinket5 $PWD/examples/Example5_SetAlertModeTemperatureLimits/Example5_SetAlertModeTemperatureLimits.ino
- arduino --verify --board adafruit:avr:protrinket5 $PWD/examples/Example6_SetConversionCycleTime/Example6_SetConversionCycleTime.ino
# - arduino --verify --board adafruit:avr:protrinket5 $PWD/examples/Example7_AdvancedI2CFunctions/Example7_AdvancedI2CFunctions.ino